SECONDS_PER_DAY = 60 * 60 * 24

DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = None

DEFAULT_MEMBER_PASSWORD = '123456'
DEFAULT_MEMBER_FUND_PASSWORD = '123456'

ROOT_MEMBER_USERNAME = 'root'
ROOT_MEMBER_PASSWORD = ''
